### ISSUE TITLE
`across2()` does not tell `mutate()` the correct used variables

### ISSUE THREAD

**Issue by psychelzh** [TimTeaFan/dplyover#22] opened 2023-12-10 06:42 UTC
See the following example:

``` r
dat <- withr::with_seed(
  1,
  data.frame(
    id = 1:5,
    x1 = rnorm(5),
    x2 = rnorm(5)
  )
)
dat |> 
  dplyr::mutate(
    dplyover::across2(
      x1:x2, x1:x2,
      cor
    ),
    .keep = "unused"
  )
#>   x1_x1 x2_x2
#> 1     1     1
#> 2     1     1
#> 3     1     1
#> 4     1     1
#> 5     1     1
```

<sup>Created on 2023-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

When specifying `.keep = "unused"`, it is expected that `id` column is kept.

**Comment by TimTeaFan** [comment] 2023-12-10 17:23
Duplicate of #1

**Closed as not planned** 2023-12-10 17:24 UTC
